[workspace]

exclude = [
"holochain-rust",
]

members = [
  "zomes/comments/code",
  "zomes/communities/code",
  "zomes/messages/code",
  "zomes/people/code",
  "zomes/posts/code",

  "common/hdk-helpers",
]
